export const SOURCE_CATALOG = [
  { id: "uschess", name: "US Chess", category: "Federation", homepage: "https://new.uschess.org/tournaments" },
  { id: "fide", name: "FIDE Tournament Calendar", category: "Federation", homepage: "https://ratings.fide.com/tournament_calendar.phtml" },
  { id: "chessevents", name: "ChessEvents", category: "Aggregator", homepage: "https://chessevents.com" },
  { id: "chessresults", name: "Chess-Results", category: "Aggregator", homepage: "https://chess-results.com" },
  { id: "cca", name: "Continental Chess Association", category: "Organizer", homepage: "https://www.continentalchess.com" },
  { id: "charlotte", name: "Charlotte Chess Center", category: "Organizer", homepage: "https://www.charlottechesscenter.org/events" },
  { id: "saintlouis", name: "Saint Louis Chess Club", category: "Organizer", homepage: "https://www.uschesschamps.com" },
  { id: "vegas", name: "Vegas Chess Festival", category: "Organizer", homepage: "https://vegaschessfestival.com" },
];

export const FALLBACK_EVENTS = [
  {
    id: "world-open-2026",
    name: "World Open",
    startDate: "2026-06-30",
    endDate: "2026-07-06",
    city: "Philadelphia",
    state: "PA",
    venue: "Sheraton Philadelphia Downtown",
    lat: 39.9583,
    lon: -75.1638,
    format: "9-round Swiss",
    entryFee: "$429-$479",
    sections: ["Open", "U2400", "U2200", "U2000", "U1800", "U1600"],
    timeControl: "G/90;+30",
    sourceId: "cca",
    sourceUrl: "https://www.continentalchess.com/worldopen/",
  },
  {
    id: "national-open-2026",
    name: "National Open",
    startDate: "2026-06-03",
    endDate: "2026-06-07",
    city: "Las Vegas",
    state: "NV",
    venue: "Flamingo Las Vegas",
    lat: 36.1162,
    lon: -115.1701,
    format: "6-round Swiss",
    entryFee: "$180-$280",
    sections: ["Open", "U2200", "U2000", "U1800", "U1600"],
    timeControl: "G/90;+30",
    sourceId: "vegas",
    sourceUrl: "https://vegaschessfestival.com",
  },
  {
    id: "charlotte-open-2026",
    name: "Charlotte Open",
    startDate: "2026-08-06",
    endDate: "2026-08-10",
    city: "Charlotte",
    state: "NC",
    venue: "Le Meridien Charlotte",
    lat: 35.2137,
    lon: -80.8557,
    format: "9-round Swiss",
    entryFee: "$199-$259",
    sections: ["Open", "U2300", "U2000", "U1700"],
    timeControl: "G/90;+30",
    sourceId: "charlotte",
    sourceUrl: "https://www.charlottechesscenter.org/events",
  },
  {
    id: "us-championship-2026",
    name: "US Championship",
    startDate: "2026-10-01",
    endDate: "2026-10-14",
    city: "Saint Louis",
    state: "MO",
    venue: "Saint Louis Chess Club",
    lat: 38.6365,
    lon: -90.2618,
    format: "Round robin",
    entryFee: "Invitation only",
    sections: ["Championship"],
    timeControl: "Classical",
    sourceId: "saintlouis",
    sourceUrl: "https://www.uschesschamps.com",
  },
  {
    id: "texas-open-2026",
    name: "Texas Open",
    startDate: "2026-04-10",
    endDate: "2026-04-12",
    city: "Houston",
    state: "TX",
    venue: "Hyatt Regency Houston",
    lat: 29.7604,
    lon: -95.3698,
    format: "5-round Swiss",
    entryFee: "$95-$145",
    sections: ["Open", "Reserve", "Novice"],
    timeControl: "G/90;+30",
    sourceId: "chessevents",
    sourceUrl: "https://chessevents.com",
  },
];

