// data.js
// Keep this file simple: it only provides a fallback dataset if events.json is missing.
// The live data should come from events.json generated by your GitHub Action.

export const FALLBACK_EVENTS = [
  // Example fallback event (optional). You can delete this entire array contents if you want.
  // {
  //   id: "fallback-sample-2026-01-01",
  //   name: "Sample Tournament (Fallback)",
  //   startDate: "2026-01-01",
  //   endDate: "2026-01-01",
  //   city: "Columbus",
  //   state: "OH",
  //   venue: "Sample Venue",
  //   lat: 39.9612,
  //   lon: -82.9988,
  //   timeControl: "G/25;d5",
  //   sections: ["Open", "U1800", "U1400"],
  //   entryFee: "$40",
  //   sourceId: "fallback",
  //   sourceUrl: "https://example.com",
  // }
];
